# Generated by Django 4.2.6 on 2023-10-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='star',
            new_name='stars',
        ),
    ]
